from setuptools import setup, find_packages

setup(
    name="AtonixCorp",
    version="0.1.0",
    author="Sam",
    author_email="ofidohub@gmail.com",
    description="A brief description of your project",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/AtonixCorp/aonixcorp",
    packages=find_packages(),
    install_requires=[
        "pyserial",
        "requests",
        "platformio",
        "arduino-cli",
        "pyfirmata",
        "opencv-python",
        "Django",
        "djangorestframework",
        "djongo",
        "pymongo",
        "gunicorn",
        "python-dotenv",
        "pandas",
        "numpy",
        "scikit-learn",
        "dask[complete]",
        "celery",
        "redis",
        "matplotlib",
        "seaborn",
        "pyspark",
        "tensorflow",
        "keras",
        "torch",
        "beautifulsoup4",
        "pytest",
        "jupyter",
        "sqlalchemy",
        "qitkit"
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)